---
title: "Creating Function"
author: "Sam Stein"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(GGally)
library(ggpubr)
library(boot)
library(kableExtra)

#setWD
setwd("~/flume_synthesis")

```

```{r data import, include=TRUE, warning=FALSE}

#import data
#flume_data_test <- read_csv("data/flume_data_test.csv") 
data <- read_excel("data/flume_review_data_eta.xlsx")

#importing function to display eqn and R2 values

lm_eqn <- function(df){
    m <- lm(y ~ x, df);
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
}

```


```{r data cleaning, include=TRUE, warning=FALSE}

data <- data %>%
  filter(!(is.na(eta))) #only include runs with eta values

#Convert from character to numeric
data$Re_c <- as.numeric(data$Re_c)
data$height <- as.numeric(data$height)
  
```


```{r aggregate and log terms, include=TRUE, warning=FALSE}

#Aggregate variables until each exponent has one associated variable

#k value = first term c5

findK <- function(Re_s, #collector Reynolds number
                  a, #front area per unit volume
                  h, #collector height
                  d #collector diameter 
                  ){
  
  k <- Re_s/((sqrt(a*h))*(1-(a*d)))

  return(k)
}

#j value = third term c7

findJ <- function(a, #frontal area per unit volume
                  d #collector diameter
){
  
  j <- a*d
  
  return(j)
}

#P value = ratio of particle density to water density
#assuming 1 g/cm^3 density of water

findP <- function(part_dense #particle density in g/cm^3
){
  
  P <- part_dense/1
  
  return(P)
}

#calculate aggregate terms

data <- data %>%
  mutate(k = findK(Re_s = Re_c, a = frontal_area_unit_volume, h = height, d = d_c)) %>%
  mutate(j = findJ(a = frontal_area_unit_volume, d = d_c)) %>%
  mutate(P = findP(part_dense = particle_density))


#log terms for later linear model fit

logdata <- data %>%
  mutate(logX1 = log(k)) %>%
  mutate(logX2 = log(radius_ratio)) %>%
  mutate(logX3 = log(j)) %>%
  mutate(logX4 = log(P)) %>%
  mutate(logY = log(eta))

#Split into Re regime
small_Re <- logdata %>%
  filter(Re_c <= 40)

large_Re <- logdata %>%
  filter(Re_c > 40)

#Isolate just biofilm runs
biofilm <- logdata %>%
  filter(biofilm == "yes")

```

```{r fit linear function, include=TRUE}

#Write function to find linear fit

findLogFit <- function(logdata){

  #Fit linear model to entire set
  #input dataset MUST have these same variable names
  
  y_hat <- logdata$logY
  logX1 <- logdata$logX1
  logX2 <- logdata$logX2
  logX3 <- logdata$logX3
  logX4 <- logdata$logX4

  linear_mod <- lm(y_hat ~ logX1 + logX2 + logX3 + logX4)

  return(linear_mod)

}

#Return linear model for entire dataset

total_lm <- findLogFit(logdata = logdata)
small_Re_lm <- findLogFit(logdata = small_Re)
large_Re_lm <- findLogFit(logdata = large_Re)
biofilm_lm <- findLogFit(logdata = biofilm)

#pulling out R2 values for plotting bootstrap CI later
total_R2 <- summary(total_lm)$r.square 
bio_R2 <- summary(biofilm_lm)$r.square
```

```{r check linear function fit, include=TRUE}

#Predict values for entire data set

logdata$predlogeta <- predict(total_lm)

all <- ggplot(logdata, aes(x = logY, y = predlogeta)) + 
  geom_smooth(method = "lm", color = "black") +
   # stat_poly_eq(formula = my.formula, 
   #              aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
   #              parse = TRUE) +
  geom_point(color = "darkblue", shape = 8, size = 1.5, alpha = .8) +
  theme_minimal() + 
  labs(title = "All Runs (R2 = 0.8914)", y = "predicted log(capture efficiency)", x = "")

#Predict for Re regimes

small_Re$predlogeta <- predict(small_Re_lm)

small <- ggplot(small_Re, aes(x = logY, y = predlogeta)) + geom_smooth(method = "lm", color = "black") +
  geom_point(color = "darkblue", shape = 8, size = 1.5, alpha = .8) +
  theme_minimal() + 
  labs(title = "Re < 40 (R2 = 0.9889)", x = "observed log(capture efficiency)", y = "predicted log(capture efficiency)")

large_Re$predlogeta <- predict(large_Re_lm)

large <- ggplot(large_Re, aes(x = logY, y = predlogeta)) + geom_smooth(method = "lm", color = "black") +
  geom_point(color = "darkblue", shape = 8, size = 1.5, alpha = .8) +
  theme_minimal() + 
  labs(title = "Re >40 (R2 = 0.8822)", x = "observed log(capture efficiency)", y = "")

#Predict for runs with biofilm presence 

biofilm$predlogeta <- predict(biofilm_lm)

bio <- ggplot(biofilm, aes(x = logY, y = predlogeta)) + geom_smooth(method = "lm", color = "black") +
  geom_point(color = "darkblue", shape = 8, size = 1.5, alpha = .8) +
  theme_minimal() + 
  labs(title = "Biofilm present (R2 = 0.9039)", x = "", y = "")


png("prelimplots.png")

ggarrange(all, bio, small, large, ncol = 2, nrow = 2)

dev.off()
```

```{r bootstrap R2, include=TRUE}

#Set up modified logfit function to return R2

bootFitR2 <- function(formula, logdata, indices){
  
  d <- logdata[indices,] # allows boot to select samples
  
  fit <- lm(formula, data=d)
 
  return(summary(fit)$r.square)  #returns R2 in vector(?) form

}

#set up bootstrap to return R2 value using 10000 bootstraps

all_R2 <- boot(data = logdata, statistic = bootFitR2,  #all data
   R=10000, formula = logY ~ logX1 + logX2 + logX3 + logX4)

biofilm_R2 <- boot(data = biofilm, statistic = bootFitR2,  #runs with biofilm
   R=10000, formula = logY ~ logX1 + logX2 + logX3 + logX4)


#Get 95% confidence intervals of bootstrapped results

all_R2_ci <- boot.ci(all_R2, conf = 0.95, type = "norm")
all_R2_min <- all_R2_ci$normal[2]
all_R2_max <- all_R2_ci$normal[3]

biofilm_R2_ci <- boot.ci(biofilm_R2, conf = 0.95, type = "norm")
biofilm_R2_min <- biofilm_R2_ci$normal[2]
biofilm_R2_max <- biofilm_R2_ci$normal[3]

#plot R2 values

all_R2_plot <- all_R2$t #extract just R2 values for all data
all_R2_plot <- as.data.frame(all_R2_plot)

biofilm_R2_plot <- biofilm_R2$t #extract just R2 values for all data
biofilm_R2_plot <- as.data.frame(biofilm_R2_plot)


ggplot(all_R2_plot) + geom_histogram(aes(x = V1), color = "lightgrey", alpha = 0.9) +
  geom_vline(aes(xintercept = all_R2_min), col="blue") +   
  geom_vline(aes(xintercept = all_R2_max), col="blue") +
  geom_vline(aes(xintercept = total_R2), col="green") +
  theme_minimal() +
  labs(title = "Bootstrapped Goodness of Fit for All Data", x = "R2 values", y = "Count (10000 total)") 

ggplot(biofilm_R2_plot) + geom_histogram(aes(x = V1), color="lightgrey", alpha = 0.9) +
  geom_vline(aes(xintercept = biofilm_R2_min), color = "blue") + 
  geom_vline(aes(xintercept = biofilm_R2_max), color = "blue") +
  geom_vline(aes(xintercept = bio_R2), col="green") +
  theme_minimal() +
  labs(title = "Bootstrapped Goodness of Fit for Runs with Biofilm", x = "R2 values", y = "Count (10000 total)")

```

```{r bootstrap coef, include=TRUE}

#Set up modified logfit function to return coefficients

bootFitCoef <- function(formula, logdata, indices){
  
  d <- logdata[indices,] # allows boot to select samples
  
  fit <- lm(formula, data=d)
 
  return(coef(fit))  #returns ceofficients in vector(?) form

}

#set up bootstrap to return coef values using 10000 bootstraps

all_coef <- boot(data = logdata, statistic = bootFitCoef,  #all data
   R=10000, formula = logY ~ logX1 + logX2 + logX3 + logX4)

biofilm_coef <- boot(data = biofilm, statistic = bootFitCoef,  #runs with biofilm
   R=10000, formula = logY ~ logX1 + logX2 + logX3 + logX4)


#95% confidence interval of bootstraps

all_coef_int <- boot.ci(all_coef, coef = 0.95, type = "bca", index = 1) #intersect
all_coef_C1 <- boot.ci(all_coef, coef = 0.95, type = "bca", index = 2) #C1
all_coef_C2 <- boot.ci(all_coef, coef = 0.95, type = "bca", index = 3) #C2
all_coef_C3 <- boot.ci(all_coef, coef = 0.95, type = "bca", index = 4) #C3
all_coef_C4 <- boot.ci(all_coef, coef = 0.95, type = "bca", index = 5) #C4

biofilm_coef_int <- boot.ci(biofilm_coef, coef = 0.95, type = "bca", index = 1) #intersect
biofilm_coef_C1 <- boot.ci(biofilm_coef, coef = 0.95, type = "bca", index = 2) #C1
biofilm_coef_C2 <- boot.ci(biofilm_coef, coef = 0.95, type = "bca", index = 3) #C2
biofilm_coef_C3 <- boot.ci(biofilm_coef, coef = 0.95, type = "bca", index = 4) #C3
biofilm_coef_C4 <- boot.ci(biofilm_coef, coef = 0.95, type = "bca", index = 5) #C4

#Extract CI values 

all_intersect <- all_coef_int$bca[4:5] #4 = min, 5 = max
all_c1 <- all_coef_C1$bca[4:5]
all_c2 <- all_coef_C2$bca[4:5]
all_c3 <- all_coef_C3$bca[4:5]
all_c4 <- all_coef_C4$bca[4:5]
all_CI <- rbind(all_intersect, all_c1, all_c2, all_c3, all_c4)
all_CI <- as.data.frame(all_CI)

biofilm_intersect <- biofilm_coef_int$bca[4:5]
biofilm_c1 <- biofilm_coef_C1$bca[4:5]
biofilm_c2 <- biofilm_coef_C2$bca[4:5]
biofilm_c3 <- biofilm_coef_C3$bca[4:5]
biofilm_c4 <- biofilm_coef_C4$bca[4:5]
biofilm_CI <- rbind(biofilm_intersect, biofilm_c1, biofilm_c2, biofilm_c3, biofilm_c4)
biofilm_CI <- as.data.frame(biofilm_CI)

#Vectors of min and max coefs
min_all <- all_CI$V1
max_all <- all_CI$V2

min_biofilm <- biofilm_CI$V1
max_biofilm <- biofilm_CI$V2

#Vectors of fitted model coefs
fit_all <- total_lm$coefficients
fit_biofilm <- biofilm_lm$coefficients

#Table with 95% CI min/max results and fitted models

table_all_fit <- rbind(min_all, fit_all, max_all) 
table_all_fit <- as.data.frame(table_all_fit) 
table_all_fit <-  table_all_fit %>%
  select(Intercept = '(Intercept)',
         C1  = logX1,
         C2 = logX2,
         C3 = logX3,
         C4 = logX4)
row.names(table_all_fit) <- c("Min", "Fit", "Max")

table_biofilm_fit <- rbind(min_biofilm, fit_biofilm, max_biofilm) 
table_biofilm_fit <- as.data.frame(table_biofilm_fit) 
table_biofilm_fit <-  table_biofilm_fit %>%
  select(Intercept = '(Intercept)',
         C1  = logX1,
         C2 = logX2,
         C3 = logX3,
         C4 = logX4)
row.names(table_biofilm_fit) <- c("Min", "Fit", "Max")

```


```{r plots with CI, include = FALSE,eval=FALS}

plotCI <- function(data, CI){
  
  logY <- CI[1] + (CI[2]*data$logX1) + (CI[3]*data$logX2) + (CI[4]*data$logX3) + (CI[5]*data$logX4)
  
  return(logY)
}


min_all_fun <- plotCI(logdata, min_all)

all_coef_plot <- all_coef$t #extract just coefs values for all data
all_coef_plot <- as.data.frame(all_coef_plot) %>%  
  select(Intercept = V1,
         C1  = V2,
         C2 = V3,
         C3 = V4,
         C4 = V5)

biofilm_coef_plot <- biofilm_coef$t #extract just coefs values for all data
biofilm_coef_plot <- as.data.frame(biofilm_coef_plot) %>%  
  select(Intercept = V1,
         C1  = V2,
         C2 = V3,
         C3 = V4,
         C4 = V5)


ggplot(all_coef_plot) + geom_histogram(aes(x = Intercept)) +
  theme_minimal() +
  labs(title = "Bootstrapped Goodness of Fit for All Data", x = "R^2 values", y = "Count (10000 total)")

ggplot(biofilm_coef_plot) + geom_histogram(aes(x = C1)) +
  theme_minimal() +
  labs(title = "Bootstrapped Goodness of Fit for Runs with Biofilm", x = "R^2 values", y = "Count (10000 total)")

```


```{r export clean dataset, include=TRUE,eval=FALSE}

#Write cleaned data file
cleandata <- logdata %>%
  select(c("run_ID", "paper", "eta", "Re_c", "frontal_area_unit_volume", "height", "d_c", "radius_ratio", "P", "logY", "logX1", "logX2", "logX3", "logX4", "predlogeta"))
  
#write.csv(subdata, file = "flume_tester_data.csv")

```
